# This is an example configuration file for udp2raw
# It is equivalent to splitting command line options into multiple lines

# Run as client
-c

# Local address
-l 0.0.0.0:56789

# Remote address
-r 45.66.77.88:45678

# Password
-k my_awesome_password

# Mode
--raw-mode faketcp

# Log Level
--log-level 4
